- # features from case flags
  prefix: 'case_flags'
  from_obj: 'staging.feature_casesflag_info LEFT JOIN staging.case_flag_lkup USING(flag)'
  knowledge_date_column: 'flag_knowledge_date'
  categoricals:
    - # case flags
      column: 'flag_id'
      choice_query: 'SELECT DISTINCT flag_id FROM staging.feature_casesflag_info LEFT JOIN staging.case_flag_lkup USING(flag)'
      metrics: ['max', 'sum']
  intervals: ['1y', '2y', '5y', '10y', '25y']
  groups: ['entity_id']
