- # features from case charges
  prefix: 'charge_info'
  from_obj: 'staging_randomized.feature_charge_info_randomized LEFT JOIN staging_randomized.charge_lkup_randomized USING(category)'
  knowledge_date_column: 'case_date'
  aggregates:
    - # more serious misdemeanor charges
      quantity: 'more_serious_flag'
      metrics: ['max', 'sum', 'avg']
    - # less serious misdemeanor charges
      quantity: 'low_level_flag'
      metrics: ['max', 'sum', 'avg']
    - # charges from LA municipal code
      quantity: 'municipal_code_flag'
      metrics: ['max', 'sum']
    - # attempts
      quantity: 'attempt_flag'
      metrics: ['max', 'sum']
    - # gang-related charges
      quantity: 'gang_related_flag'
      metrics: ['max', 'sum', 'avg']
    # - # alchohol-related charges
    #   quantity: 'alcohol_related_flag'
    #   metrics: ['max', 'sum', 'avg']
    # - # drug use charges
    #   quantity: 'drug_use_flag'
    #   metrics: ['max', 'sum', 'avg']
    # - # protective order violations
    #   quantity: 'protective_order_flag'
    #   metrics: ['max', 'sum', 'avg']
    # - # probation violations
    #   quantity: probation_violation_flag
    #   metrics: ['max', 'sum', 'avg']
  categoricals:
    - # type of charge
      column: 'chrg_cat_id'
      choice_query: 'SELECT DISTINCT chrg_cat_id FROM staging_randomized.feature_charge_info_randomized LEFT JOIN staging_randomized.charge_lkup_randomized USING(category)'
      metrics: ['max', 'sum']
    - # top-level section
      column: 'section_prefix'
      choice_query: 'SELECT DISTINCT section_prefix FROM staging_randomized.feature_charge_info_randomized'
      metrics: ['max', 'sum']
  intervals: ['1y', '2y', '5y', '10y', '50y']
  groups: ['entity_id']
